#ifndef CONSTANT_ANIMATION_FRAME_H_INCLUDED
#define CONSTANT_ANIMATION_FRAME_H_INCLUDED

// The frames used by On_Screen type. Not all are used by each type.
enum {	CLIP_GAUGE_CT, CLIP_GAUGE_YS, CLIP_GAUGE_CXX, CLIP_TARGET_REDICAL, CLIP_MENU_RETURN_BUTTON,  CLIP_MENU_SWITCH_BUTTON, CLIP_MENU_SWITCH_BUTTON_EXPAND1,
		CLIP_MENU_SAVE_BUTTON, CLIP_MENU_SWITCH_YS_ICON, CLIP_MENU_SWITCH_CYRON_ICON, CLIP_MENU_SWITCH_CXX120_ICON,
		HEALTH_0, HEALTH_1, HEALTH_2, HEALTH_3, HEALTH_4, HEALTH_5, HEALTH_6, HEALTH_7, HEALTH_8, HEALTH_9,
		HEALTH_10, HEALTH_11, HEALTH_12, HEALTH_13, HEALTH_14, HEALTH_15, HEALTH_16, HEALTH_17, HEALTH_18, HEALTH_19,
		HEALTH_20, HEALTH_21,
  
 };



//Screen Effects
enum {	CLIP_TITLE_SCREEN, CLIP_BLACK_BG, CLIP_CYRON_SAVE_MENU, CLIP_RGB_ROAD_SKY1,  
		CLIP_RGB_ROAD_SKY2, CLIP_RGB_ROAD_SKY3, CLIP_RGB_ROAD_SKY4
  
 };


#endif